# Generated by Django 5.2.17 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_generationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleresult',
            name='sheet_row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='spreadsheet_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
