# Generated by Django 5.2.17 on 2026-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_articleresult_sheet_row_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='output_sheet_url',
            field=models.URLField(blank=True, help_text='URL of the new Google Sheet with the generated articles, shared with the user.', null=True),
        ),
    ]
