# Generated by Django 5.2.17 on 2026-08-09 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_generationjob_output_sheet_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The logged-in user who owns this job; used to share the output sheet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
