# Generated by Django 5.2.17 on 2026-08-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_generationjob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationjob',
            name='output_file',
        ),
    ]
