# Generated by Django 5.2.17 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_remove_generationjob_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Any error that occurred while creating/sharing the output sheet.'),
        ),
    ]
