# Generated by Django 5.2.17 on 2026-08-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_generationjob_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationjob',
            name='error_message',
        ),
    ]
