# Generated by Django 5.2.17 on 2026-08-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_remove_generationjob_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleresult',
            name='sheet_row_number',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='output_sheet_url',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='uploaded_file',
        ),
    ]
