# Generated by Django 5.2.17 on 2026-08-16 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_remove_articleresult_sheet_row_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The logged-in user who started this job (optional, for auditing).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articleresult',
            index=models.Index(fields=['job', 'status'], name='article_job_status_idx'),
        ),
    ]
